spring:
  application:
    name: blog-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://config-service.config.svc.cluster.local:8888
      name: blog-service
      label: main
      fail-fast: true
  profiles:
    active: cloud


logging:
  level:
    org.springframework.boot.context.config: debug
server:
  port: 8070